[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
UnitfulLatexify = "45397f5d-5981-4c77-b2b3-fc36d6e9b728"
UnitfulLinearAlgebra = "c14bd059-d406-4571-8f61-9bd20e53c30b"
